name: Get modified files

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  get_files:
    name: run_on_pr_or_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - uses: hmarr/debug-action@v3
      
      - name: Get list of modified files
        id: modified-files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const event = context.eventName;
            let files = [];
            if (event === 'push') {
              const pushPayload = context.payload;
              files = pushPayload.commits.flatMap(commit => commit.modified);
            } else if (event === 'pull_request') {
              const prNumber = context.payload.pull_request.number;
              console.log(`PR: ${prNumber}`);
              const { data: pullRequestFiles } = await github.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
              files = pullRequestFiles.map(file => file.filename);
            }
            return files;

      - name: Output modified files
        run: |
          echo "Modified files: ${{ steps.modified-files.outputs.result }}"
