name: Get modified files

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  get_files:
    name: run_on_pr_or_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Modified files
        run: |
          case '${{ github.event_name }}' in
            push)
              echo "is push"
              firstCommit='${{ github.event.commits[0].id }}'
              lastCommit='${{ github.event.commits[-1].id }}'
              ;;
            pull_request)
              echo "is pr"
              firstCommit='${{ github.event.base_ref }}'
              lastCommit='${{ github.event.head_ref }}'
              ;;
          esac
          echo "first commit ${firstCommit} last commit ${lastCommit}"
          # changedFiles=$(git diff --name-only --diff-filter=d "${firstCommit}~1" "${lastCommit}")
